trading_params:
  symbol: "PERP_WOO_USDT"
  time_interval: 5000
  tick_size: 0.0001
  limit_quantity_decimals: 0
  single_position_size: 30
  init_capital: 500

subscription_params:
  symbol: "PERP_WOO_USDT"
  market_config:
    orderbook: True
    bbo: False
    trade: True
    kline: False
    markprice: True
  private_config:
    executionreport: True
    position: False
    balance: False
  
risk_params:
  max_position_size: 0.1
  stop_loss_pct: 0.05
  take_profit_pct: 0.30