trading_params:
  symbol: "PERP_BTC_USDT"
  time_interval: 5000
  tick_size: 1
  limit_quantity_decimals: 4
  single_position_size: 30

subscription_params:
  symbol: "PERP_BTC_USDT"
  market_config:
    orderbook: True
    bbo: False
    trade: False
    kline: False
  private_config:
    executionreport: True
    position: False
    balance: False
  
risk_params:
  max_position_size: 0.1
  stop_loss_pct: 0.05
  take_profit_pct: 0.30
