trading_params:
  symbol: "PERP_ETH_USDT"
  time_interval: 20000
  tick_size: 0.1
  limit_quantity_decimals: 4
  single_position_size: 500
  init_capital: 25000
  grid_depth: 5
  spread_percentage: 0.2

subscription_params:
  symbol: "PERP_ETH_USDT"
  market_config:
    orderbook: True
    bbo: False
    trades: True
    kline: False
    markprice: True
  private_config:
    executionreport: True
    position: False
    balance: False
  
risk_params:
  max_position_size: 0.1
  stop_loss_pct: 0.05
  take_profit_pct: 0.30
